### ISSUE TITLE
storage: document limitation?

### ISSUE THREAD

**Issue by pelikhan** [lancaster-university/microbit-dal#123]
Could you add more "limitation" notes about the storage? max size of key, value, computational cost of lookup / update.

It seems that the flash is rewritten on each update so updating the value in a tight loop is probably not the best of ideas if one has many keys?

**Comment by jamesadevine** [comment]
@pelikhan http://lancaster-university.github.io/microbit-docs/ubit/storage/#operations Do you feel it would be better to add this to the header files then?

Yes, flash is rewritten on each update. This storage module is intended to be purely used for lightweight, occasional operations, @alexk2k12's file system would be a better solution for large amounts of data.

**Comment by mmoskal** [comment]
Also, the doc say you have to free KeyValuePair, but the example doesn't.

**Comment by jamesadevine** [comment]
@mmoskal Great point, that is an example of bad practice 😉  although that example doesn't strictly need it. Will update, thanks for pointing that out!

**Comment by jamesadevine** [comment]
@mmoskal @pelikhan Documentation has been updated on the docs-site, do you feel anything else needs to be done here?

**Comment by mmoskal** [comment]
Looks good!
