### ISSUE TITLE
MicroBitIOPinService scans more pins than MicroBitIO has

### ISSUE THREAD

**Issue by martinwork** [lancaster-university/microbit-dal#127]
MicroBitIO has 19 pins but MICROBIT_IO_PIN_SERVICE_PINCOUNT is 20.

So I think the for loops in MicroBitIOPinService, with range >=0 and <20, scan one beyond io.P20.

**Comment by jamesadevine** [comment]
I believe your pull #135 fixed this issue.

Closing!
