### ISSUE TITLE
Incorrect sequencing in Radio IRQ handler?

### ISSUE THREAD

**Issue by whs-che** [lancaster-university/microbit-dal#150]
I wrote a simple checksum algorithm at my application level when I suspected packet corruption. To my surprise it did actually trap errors. I was rather hoping the lower level routines would discard packets with a bad CRC check. I then thought that maybe this was deliberate for education purposes and that the rssi value (only updated if no CRC error) was intended as an indication of the failure (value 0 maybe?). This does not work for two reasons: firstly the rssi is never explicitly set under a CRC fault and would rely on a memory allocation doing so and secondly the rssi value appears to be stored in the context of of the new receive buffer and not the one which has just been sent to the queue.

Without knowing the original intention I have fixed the problem by calling the following  two lines of code only if the CRC is okay and not at the start of the routine as in the current version:
latest rssi value must be set before this is called.

``` 
// Move on to the next buffer, if possible.
            MicroBitRadio::instance->queueRxBuf();
            NRF_RADIO->PACKETPTR = (uint32_t) MicroBitRadio::instance->getRxBuf();
```
Note that queueRxBuf() internally takes the last rssi value and queues before it has chance to be updated if called at the start of the ISR.

There's a distinct possibility that I will cause unintended side effects with this mod but all I know for now is that it's working perfectly. 

Hope this all makes sense and is of some help.

Added final code for clarity
```
extern "C" void RADIO_IRQHandler(void)
{
    if(NRF_RADIO->EVENTS_READY)
    {
        NRF_RADIO->EVENTS_READY = 0;
        // Start listening and wait for the END event
        NRF_RADIO->TASKS_START = 1;
    }
    if(NRF_RADIO->EVENTS_END)
    {
        NRF_RADIO->EVENTS_END = 0;
        if(NRF_RADIO->CRCSTATUS == 1)
        {
            uint8_t sample = NRF_RADIO->RSSISAMPLE;
            // Associate this packet's rssi value with the data just 
            // transferred by DMA receive
            MicroBitRadio::instance->setRSSI(sample);
            // Now move on to the next buffer, if possible.
            // The queued packet will get the rssi value set above.
            MicroBitRadio::instance->queueRxBuf();
            // Set the new buffer for DMA
            NRF_RADIO->PACKETPTR = (uint32_t) MicroBitRadio::instance->getRxBuf();
        }
        else
        {
            MicroBitRadio::instance->setRSSI(0);
        }

        // Start listening and wait for the END event
        NRF_RADIO->TASKS_START = 1;
    }
}
```

**Comment by finneyj** [comment]
@whs-che 

Many thanks for feeding this back - this is indeed a missed validation check, and this looks like a good fix. Would you like to present it as a pull request so we can merge this in wit your attribution?

**Comment by finneyj** [comment]
@whs-che 

I've tested and merged your bugfix documented here. Thanks for the contribution!
https://github.com/lancaster-university/microbit-dal/commit/07b6f7f6b65e9b566c86abe7c471ad7dfb41851e
