### ISSUE TITLE
netbeans reports yotta_cfg_mappings.h as missing include in MicroBitConfig.h

### ISSUE THREAD

**Issue by drmpf** [lancaster-university/microbit-dal#184]
Compiling the BLE uart example, netbeans reports
 yotta_cfg_mappings.h as missing include in MicroBitConfig.h
changing 
#include "yotta_cfg_mappings.h"
to 
#include "../platform/yotta_cfg_mappings.h"
resolves the issue, but not sure why it was not found.

**Comment by jamesadevine** [comment]
@drmpf That's weird! And it has no troubles with other headers?

**Comment by drmpf** [comment]
Yes, I agree, weird.  No trouble with other headers, except the [missing sleep_api.h header](https://github.com/lancaster-university/mbed-classic/issues/1)

**Comment by drmpf** [comment]
As noted in  [missing sleep_api.h header](https://github.com/lancaster-university/mbed-classic/issues/1) this is a Netbeans code include processing issue.  It does not effect building only code navigation within Netbeans. 
So closing this issue also.
