### ISSUE TITLE
Broken link to Microbit profile PDF

### ISSUE THREAD

**Issue by pelikhan** [lancaster-university/microbit-dal#221]
The link to the microbit profile is broken: https://lancaster-university.github.io/microbit-docs/ble/event-service/

**Comment by bluetooth-mdw** [comment]
Sorry, it's no longer a PDF. Can you change the URL to the following please?

**Comment by finneyj** [comment]
thanks @pelikhan @bluetooth-mdw. Just updated all docs to refer to this page. Docs should go live with next release.
