### ISSUE TITLE
Strings with // are converted to \ on the microbit

### ISSUE THREAD

**Issue by microsoftsam** [lancaster-university/microbit-dal#258]
Two forward slashes are converted into a backslash on the microbit. 

It seems the issue is in the DisplayDriver's print function.

**Comment by microsoftsam** [comment]
Turns out this isn't a dal issue.

**Comment by finneyj** [comment]
ok - thanks for clarifying @microsoftsam

**Comment by OwenBrotherwood** [comment]
pxt 911 will soon be closing
![image](https://cloud.githubusercontent.com/assets/866122/21907567/4f24c14e-d910-11e6-87a6-e5f2d50f11b9.png)
