### ISSUE TITLE
Configure the queue for radio signals

### ISSUE THREAD

**Issue by jessiejc23** [lancaster-university/microbit-dal#260]
How do I configure the queue of radio packets (?) for the radio function? Managed to configure the data throughput and length of messages so far. 

I suspect that changes are to be made in MicroBitRadio.cpp and MicroBitRadio.h just like what I did to configure the length of messages and throughput.

**Comment by finneyj** [comment]
hi @jessiejc23, 

The maximum size of the queue is currently a compile time configuration defined here:
https://github.com/lancaster-university/microbit-dal/blob/master/inc/drivers/MicroBitRadio.h#L71

So if you change this value and recompile microbit-dal then I think this should have the behaviour you're looking for.
