### ISSUE TITLE
MIT licence missing from some files

### ISSUE THREAD

**Issue by whaleygeek** [lancaster-university/microbit-dal#269]
The MIT licence header is missing from these files:

drivers/MicroBitFile.h 
drivers/MicroBitFileSystem.h
drivers/MicroBitFlash.h

drivers/MicroBitFile.cpp
drivers/MicroBitFileSystem.cpp
drivers/MicroBitFlash.cpp

**Comment by finneyj** [comment]
Thanks. Will fix.

**Comment by alennie1993** [comment]
Added in and PR sent, closing issue.
