### ISSUE TITLE
BLE time client

### ISSUE THREAD

**Issue by OwenBrotherwood** [lancaster-university/microbit-dal#273]
Hi
I wonder if there is room for a BLE time client on the micro:bit?

If DAL can expose the result of a successful collection of real time relative to the world from a BLE time servicet his would give applications that need it, some form of real time indication.

In short form, on power on, start asking for the time, with options for always or just for a certain time period, from any nearby BLE time server that could be on a PC or mobil.

The nRF5X has a timer onboard, so real time snapshot plus timer gives real time

It should be noted, that on download of hex one could have a timestamp that could be used, but possibly the above is a solution as on power loss, no reference and with download of hex, there is often a bluetooth transmitter nearby anyway.

https://developer.nordicsemi.com/nRF5_SDK/nRF51_SDK_v8.x.x/doc/8.0.0/s110/html/a00064.html

---

The option for only ask for time for a period is to ensure that power is not drained.

It could also be "nice" to have a time server on the micro:bit, but time client is perceived as being the requirement "just now"

**Comment by OwenBrotherwood** [comment]
@bluetooth-mdw 
Hi Mr Bluetooth :) , 
Any thoughts about this?

**Comment by finneyj** [comment]
Hi @OwenBrotherwood 

This is a great idea - An NTP style real time clock would definitely be useful. Once we have a snapshot, the rest would be fairly straightforward to implement. I'm not so sure this service is feasible though, as we cna only realistically run S110 at the moment, which gives us BLE peripheral capabilities, but not BLE client capabilities. I'm not 100% sure, but scanning the docs you referenced, it sounds like we'd need BLE client operation to enable this?

p.s. I think Mr Bluetooth is on a well deserved holiday at the moment...

**Comment by OwenBrotherwood** [comment]
Just a short comment, on the nRF android (and other) sw from nordic, a time service is a couple of clicks to enablement

**Comment by bluetooth-mdw** [comment]
The Nordic info does indeed describe the GATT client end of the standard Current Time Profile so we couldn't do this with S110.

**Comment by finneyj** [comment]
Thanks @bluetooth-mdw. I'll close this one off for now then, as our current memory limitations won't let us realistically go beyond S110...

**Comment by OwenBrotherwood** [comment]
micro:bit v52 :)
