### ISSUE TITLE
Strange servo behaviour

### ISSUE THREAD

**Issue by DavidWhaleMEF** [lancaster-university/microbit-dal#278]
@finneyj any thoughts about this one:

https://github.com/Microsoft/pxt/issues/1399

**Comment by finneyj** [comment]
hmm... does sound like an issue with the new PWM driver.  Maybe the updating in a tight loop.

Odd that Dave is reporting different behaviour with blocks and JS though.

**Comment by finneyj** [comment]
@DavidWhaleIET Closing this off. As discussed in Microsoft/pxt#1399 this has already been resolved in #264
