### ISSUE TITLE
warning cleanup

### ISSUE THREAD

**Issue by mmoskal** [lancaster-university/microbit-dal#33]
Creating issue from comments on #32 , which are unrelated to the main reason for that pull req.

https://github.com/lancaster-university/microbit-dal/pull/32#discussion-diff-43133239

```
+#pragma GCC diagnostic ignored "-Wunused-parameter"
+#pragma GCC diagnostic ignored "-Wconversion-null"
+#pragma GCC diagnostic ignored "-Wsign-compare"
+#pragma GCC diagnostic ignored "-Wparentheses"
+#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
```

Relevant links:
https://gcc.gnu.org/onlinedocs/gcc/Diagnostic-Pragmas.html
https://gcc.gnu.org/onlinedocs/cpp/System-Headers.html

CC @remay @finneyj

**Comment by jamesadevine** [comment]
@mmoskal All warnings in the dal have been corrected, and warnings from underlying libraries have been suppressed.

Thanks for your work on this @remay, closing.
