### ISSUE TITLE
Feature request: basic.once(() => {  })

### ISSUE THREAD

**Issue by ltagliaro** [lancaster-university/microbit-dal#344]
Hello, 

it would be useful to have the possibility to schedule the execution of an asynchronous action. Of course, such a primitive would not be used as a top level statement but inside a block of statements. An example would be in a game: some event or condition may trigger the launch of an animation, which would take some time to complete, but at the same time the processing of the logic must continue without any delay.

Best regards

Lorenzo

**Comment by pelikhan** [comment]
We missed this feature request. Could you reopen it at https://github.com/microsoft/pxt-microbit/issues ?
