### ISSUE TITLE
This repository should be public and open-source.

### ISSUE THREAD

**Issue by markshannon** [lancaster-university/microbit-dal#35]
https://github.com/bbcmicrobit/micropython is now open source, so why not this?

**Comment by remay** [comment]
@finneyj Thank you for all your work - that's a pretty big step forwards.  Now I need to find the time to move my work on top of the latest and greatest ...

**Comment by ntoll** [comment]
Stonkingly good stuff. Care to close this issue? ;-)

**Comment by finneyj** [comment]
yup - just thought i'd leave open a few days in case folks wanted to comment. ;-)

**Comment by ntoll** [comment]
Funnily enough... it's possible to comment on a closed issue. ;-)

(In a "what sound does a falling tree make in an empty forest?" sort of a way I guess...)
