### ISSUE TITLE
Separate the HAL from the mini-OS/Touch-develop runtime

### ISSUE THREAD

**Issue by markshannon** [lancaster-university/microbit-dal#40]
The DAL currently consists of a genuine hardware abstraction layer (HAL) and an assortment of lightweight OS and language runtime features.
Unfortunately it is currently impossible to use the  HAL without getting all the other stuff.
For MicroPython and, I suspect other systems, it would be highly desirable to have access to the HAL without having to work around the other features.

For the specific case of MicroPython on the micro:bit we need the following features that the DAL provides:
* reset
* I2C
* PWM
* Pins
* Pin de-bouncing (currently residing in the Button class)
* Compass
* Accelerometer
* Font
* UART/serial (although the underlying mbed class may be sufficient)

We *don't* need the following features:
* Heap allocator
* Fibers
* Events, Message Bus and Listeners
* Managed Strings
* Image
* Button (apart from the de-bouncing logic)
* MultiButton

I've deliberately not mentioned the display or BLE on either list.
MicroPython already has its own implementation of the display, so we don't need the DAL display. 
However it might save some code duplication if the lowest level functionality of the display were exposed. A stand alone `panic()` function would also be useful.

Separating out the BLE related parts will be more complex, and best left for later.

Ideally we will be able to replace `#include "MicroBit.h"` with `#include "MicroBitHal.h` in the MicroPython code and save ourselves the overhead of the unwanted features.

**Comment by jamesadevine** [comment]
Hi @markshannon, we have now merged in the component-refactor branch which leads to a componentised DAL. Happy to receive comments regarding any further changes you think are required!

Closing this one for now though!
