### ISSUE TITLE
Support for full flashing with Partial Flashing code

### ISSUE THREAD

**Issue by pelikhan** [lancaster-university/microbit-dal#415]
Is there any reason why we would not completely remove the DFU service and use the Partial Flashing service to flash the full image?

**Comment by martinwork** [comment]
The partial flashing service code is part of the full image.

**Comment by jaustin** [comment]
Closing as Martin's answer is about as complete - we can't clobber ourselves over BLE. The reason the existing DFU service works well is that it fits in 16KB Flash as a standalone image that doesn't require any other infrastructure
