### ISSUE TITLE
Micro Bit 2 and Dal

### ISSUE THREAD

**Issue by JamesEBrooks** [lancaster-university/microbit-dal#473]
Will information be put up online for working with the new Micro Bit and Dal. I'm using VS code.

**Comment by carlosperate** [comment]
The new micro:bit uses CODAL: https://github.com/lancaster-university/codal-microbit-v2
This samples repo is a good starting point to create CODAL programmes: https://github.com/lancaster-university/microbit-v2-samples

**Comment by JamesEBrooks** [comment]
Ah thanks carlosperate. I don't have one yet but t his is a great start. Thanks
