### ISSUE TITLE
Add hardware version to BLE device information service, model number string

### ISSUE THREAD

**Issue by martinwork** [lancaster-university/microbit-dal#478]
See https://github.com/lancaster-university/codal-microbit-v2/issues/77

Also https://github.com/lancaster-university/microbit-dal/pull/373

**Comment by microbit-carlos** [comment]
We ended up removing the the differentiation between 2.0 & 2.2, and left it as "BBC micro:bit V2".

We've consider if we wanted to change DAL to "BBC micro:bit V1", but decided against as it has been like this for 3 year and any BLE apps wanted to tell them apart can already do that from the "V2" part.
