### ISSUE TITLE
Is it possible to change the brightness of power indicator LED programmatically?

### ISSUE THREAD

**Issue by goldenbull** [lancaster-university/microbit-dal#483]
as title.

**Comment by carlosperate** [comment]
Not from DAL/CODAL, sorry. The power red LED next to the USB connector is controlled by the "interface chip", which is a secondary microcontroller running DAPLink.
You could modify DAPLink to change the LED brightness (and even to change it via I2C messages!) if you'd like:
- https://github.com/ARMmbed/DAPLink
- https://tech.microbit.org/software/daplink-interface/

**Comment by goldenbull** [comment]
thanks @carlosperate
