### ISSUE TITLE
triple-tap-reset to enter pairing mode

### ISSUE THREAD

**Issue by jaustin** [lancaster-university/microbit-dal#486]
in CODAL we've implemented a really nice feature that lets a user enter pairing mode by triple-tapping the reset button.

https://github.com/lancaster-university/codal-microbit-v2/tree/triple-reset-to-pair

For us to move to this as the primary pairing mechanism we'll need to ensure it's in microbit-dal too.

@finneyj @JohnVidler could you please port this to microbit-dal before we make the next DAL release?

**Comment by whaleygeek** [comment]
@jaustin See this, for some motivation to get this done!!!

https://twitter.com/jerseyitguy/status/1622205053640622080

**Comment by microbit-carlos** [comment]
We working on this ticket we can take the opportunity and remove some start up delays as well: 
https://github.com/lancaster-university/microbit/blob/1d1baa561f82ab0d16d1916b0026955c67d95e74/source/MicroBit.cpp#L133

**Comment by martinwork** [comment]
See https://github.com/lancaster-university/codal-microbit-v2/issues/348

**Comment by martinwork** [comment]
Created https://github.com/lancaster-university/microbit/pull/20 with animation delay reduced form 50ms to 20ms.

@microbit-carlos Would you like me also to remove the 100ms delay?
https://github.com/lancaster-university/microbit/blob/1d1baa561f82ab0d16d1916b0026955c67d95e74/source/MicroBit.cpp#L133
I don't see any evidence as to why it was added, but it seems to have always been there.

**Comment by carlosperate** [comment]
@finneyj when you were looking at startup timings for the tripple-press-to-pair in V1 DAL, did you notice the delay's from Martin last comment? And do you know if they are safe to remove? (or worth removing?)

**Comment by microbit-carlos** [comment]
Any solutions we have thought about to tackle this feature are too invasive or complex, so we've decided not to implement triple reset to pair mode in V1.
