### ISSUE TITLE
Calibrating the compass has insane side effects.

### ISSUE THREAD

**Issue by markshannon** [lancaster-university/microbit-dal#82]
Calling `compass.calibrate()` forces the user play some sort of "game" as a side effect.
The behaviour of `compass.calibrateAsync()` has been changed without warning to mimic `compass.calibrate()`.

This "game" presumes the availability of `MicroBitDisplay` and `MicroBitImage` which breaks MicroPython, as we don't use those, having better alternatives.

Please revert this crazy behaviour  ASAP.

**Comment by jamesadevine** [comment]
I feel that this has been suitably addressed by the many commits since Jan 27.

Closing.
