### ISSUE TITLE
External touch support on other pins

### ISSUE THREAD

**Issue by gbaman** [lancaster-university/microbit-dal#90]
So the Microbit has 3 pins with resistors to 3v which I believe are 22M ohms (although not sure without a real schematic..), doing this allows the pin to be set up as a resistive touch input, Makey Makey style. These resistors are on 0, 1 and 2.
As part of a project, we needed 7 touch inputs. Of course the hardware on the Microbit itself didn't support that, but with the additional of some external 22M ohm resistors (costing mere pennies) on a breadboard with some simple wiring, you can add the hardware required to add it onto any of the other non LED matrix or buttons pins.
After a bit of DAL and Micropython hacking, we got it working and the result can be seen here https://twitter.com/elsie_m_/status/694673753293373441.

So I think it would be worth starting the discussion if it is worth looking at changing it in the DAL to support this somehow. Obviously we don't want it enabled by default, am wondering if there is some way it can be enabled on the fly? If the student knows what they are doing, there is some way support can be enabled, as right now is it hard coded off in [MicroBitIO.cpp](https://github.com/lancaster-university/microbit-dal/blob/master/source/MicroBitIO.cpp).
It is then as simple for example in Micropython, to also enable support. 
The code required to make a 7 key piano is then super simple in Python for example - [keyboard.py](https://gist.github.com/gbaman/8271f1b3149e4c2e2dad).
Wiring wise, it isn't that complicated either
![421222185_15794239954575914120](https://cloud.githubusercontent.com/assets/833193/12794161/9e42abca-caab-11e5-9225-2b5b9b42cbff.jpg)

Opinions? I am not sure the best way to do it, but think is worth starting a discussion on it.

**Comment by gbaman** [comment]
Anything further on this? Would be great for kids to be able to make this without having to use the presupplied .hex file or hacking their own DAL :)

**Comment by finneyj** [comment]
Apologies @gbaman - Beeb have been keeping us busy with support for wellcome trust experiment. not as much time as we'd like to pick up these issues... hope you understand. 

I'll push an update to master today that includes support for this, and will be in the next 2.0.0 release candidate.

I'm not sure which version micropython are referencing though - I'm guessing 1.4.x?

**Comment by carlosperate** [comment]
1.4.15 currently: https://github.com/bbcmicrobit/micropython/blob/master/module.json#L11

**Comment by finneyj** [comment]
ok - thanks @carlosperate. 

This would be an easy patch to backport. We can tag a 1.4.x branch also if that would help?

**Comment by jamesadevine** [comment]
@finneyj @gbaman fixed locally, going to do further testing tomorrow and will merge into master.

**Comment by finneyj** [comment]
thanks @jamesadevine

**Comment by jamesadevine** [comment]
@gbaman Once again apologies for the delay.

The update is now in master!

Here are the results of my testing (with the display disabled):

| Pin number | Touch|
|------------|-------|
| 3 (COL1)         | Yes    |
| 4  (COL2)       | Yes    |
| 5 (BTN_A)         | No    |
| 6  (COL9)         | Yes   |
| 7  (COL8)          | Yes   |
| 8         | Yes   |
| 9   (COL7)         | Yes    |
| 10   (COL3)        | Yes   |
| 11     (BTN_B)      | No   |
| 12   (ACCESS)        | Yes   |
| 13   (SCK)        | Yes   |
| 14   (MISO)      | Yes   |
| 15    (MOSI)      | Yes   |
| 16        | Yes   |

Here is my setup:

![img_3398](https://cloud.githubusercontent.com/assets/4742697/15111907/322c236c-15e2-11e6-86ba-024c8c4c2605.JPG)

(The resistor is 10M).

My test program:

```
int main()
{
    // Initialise the micro:bit runtime.
    uBit.init();
    
    uBit.display.scroll("Starting!");
    uBit.display.disable();

    while(1)
    {
        for(int i = 3; i < 20; i++)
        {
            uBit.serial.printf("P%d\r\n",i);
            
            uBit.io.pin[i].isTouched();
            
            int j = 0;
            int state = 0;
            int previousState = 0;
            while(j < 2000)
            {
                state = uBit.io.pin[i].isTouched();
                
                if(state && !previousState)
                    uBit.serial.printf("DOWN\r\n");
                
                if(!state && previousState)
                    uBit.serial.printf("UP\r\n");
                
                previousState = state;
                
                uBit.sleep(10);
                j++;
            }
            
            uBit.io.pin[i].setDigitalValue(0);
        }
    }

    release_fiber();
}
```

I can't attest to how the micropython display driver disables the display, @markshannon?

**Comment by jamesadevine** [comment]
In v2.0.0-rc3.
