### ISSUE TITLE
datagram.recv() problem

### ISSUE THREAD

**Issue by mmoskal** [lancaster-university/microbit-dal#94]
https://github.com/lancaster-university/microbit-dal/blob/master/source/ble-services/MicroBitRadioDatagram.cpp#L58

There is no protection for the queue being empty there

**Comment by finneyj** [comment]
@mmoskal For closure - this was fixed a while ago, version 1.4.16 or later.

**Comment by mmoskal** [comment]
Yap, I've seen that, thanks!
