### ISSUE TITLE
Serial data transfer capability over Bluetooth

### ISSUE THREAD

**Issue by bluetooth-mdw** [lancaster-university/microbit-dal#95]
Microsoft in the UK have a requirement to transfer digital photographs captured by a device connected to the micro:bit edge connector over Bluetooth to another device. The Bluetooth profile as currently defined does not support this use case. 

Suggest evaluating the possibility of including Nordic's UART service as an optional service which is disabled from builds by default.

**Comment by jamesadevine** [comment]
@bluetooth-mdw the capability is there now - closing!
